In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('/content/purchase_data (1).csv')
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10.0,A,2,0.0,3.0,NaN,NaN,8370.0
1,1000001,P00248942,F,0-17,10.0,A,2,0.0,1.0,6.0,14.0,15200.0
2,1000001,P00087842,F,0-17,10.0,A,2,0.0,12.0,NaN,NaN,1422.0
3,1000001,P00085442,F,0-17,10.0,A,2,0.0,12.0,14.0,NaN,1057.0
4,1000002,P00285442,M,55+,16.0,C,4+,0.0,8.0,NaN,NaN,7969.0
...,...,...,...,...,...,...,...,...,...,...,...,...
263010,1004473,P00041942,M,36-45,1.0,B,3,0.0,5.0,18.0,NaN,3722.0
263011,1004473,P00115142,M,36-45,1.0,B,3,0.0,1.0,8.0,17.0,19253.0
263012,1004473,P00188442,M,36-45,1.0,B,3,0.0,5.0,7.0,NaN,3608.0
263013,1004473,P00119442,M,36-45,1.0,B,3,0.0,5.0,NaN,NaN,3604.0
263014,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
#EDA -- Exploratory Data Analysis
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263015 entries, 0 to 263014
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     263015 non-null  int64
 1   Product_ID                  263014 non-null  object
 2   Gender                      263014 non-null  object
 3   Age                         263014 non-null  object
 4   Occupation                  263014 non-null  float64
 5   City_Category               263014 non-null  object
 6   Stay_In_Current_City_Years  263014 non-null  object
 7   Marital_Status              263014 non-null  float64
 8   Product_Category_1          263014 non-null  float64
 9   Product_Category_2          181501 non-null  float64
 10  Product_Category_3          80582 non-null   float64
 11  Purchase                    263014 non-null  float64
dtypes: float64(6), int64(1), object(5)
memory usage: 24.1+ MB

In [4]:
data['Stay_In_Current_City_Years'].unique()

array(['2', '4+', '3', '1', '0', nan], dtype=object)

In [5]:
data['Stay_In_Current_City_Years'] = pd.to_numeric(data['Stay_In_Current_City_Years'],errors='coerce')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263015 entries, 0 to 263014
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     263015 non-null  int64
 1   Product_ID                  263014 non-null  object
 2   Gender                      263014 non-null  object
 3   Age                         263014 non-null  object
 4   Occupation                  263014 non-null  float64
 5   City_Category               263014 non-null  object
 6   Stay_In_Current_City_Years  222349 non-null  float64
 7   Marital_Status              263014 non-null  float64
 8   Product_Category_1          263014 non-null  float64
 9   Product_Category_2          181501 non-null  float64
 10  Product_Category_3          80582 non-null   float64
 11  Purchase                    263014 non-null  float64
dtypes: float64(7), int64(1), object(4)
memory usage: 24.1+ MB

In [7]:
data['Stay_In_Current_City_Years'].unique()

array([ 2., nan,  3.,  1.,  0.])

In [9]:
data['Age'].value_counts()

Age
0-17       7064
55+       10321
51-55     18509
46-50     21619
18-25     48193
36-45     52396
26-35    104912
Name: count, dtype: int64

In [10]:
data['Age'].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25', nan],
      dtype=object)

In [16]:
data.isnull().sum()

User_ID                            0
Product_ID                         1
Gender                             1
Age                                1
Occupation                         1
City_Category                      1
Stay_In_Current_City_Years     40666
Marital_Status                     1
Product_Category_1                 1
Product_Category_2             81514
Product_Category_3            182433
Purchase                           1
dtype: int64

In [17]:
data['Product_Category_2'].fillna(0,inplace=True)
data['Product_Category_3'].fillna(0,inplace=True)

/tmp/ipython-input-731683015.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Product_Category_2'].fillna(0,inplace=True)
/tmp/ipython-input-731683015.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Product_Category_3'].fillna(0,inplace=True)

In [18]:
data.isnull().sum()

User_ID                           0
Product_ID                        1
Gender                            1
Age                               1
Occupation                        1
City_Category                     1
Stay_In_Current_City_Years    40666
Marital_Status                    1
Product_Category_1                1
Product_Category_2                0
Product_Category_3                0
Purchase                          1
dtype: int64

In [19]:
data.dropna(inplace=True)

In [21]:
data.isnull().sum()

User_ID                       0
Product_ID                    0
Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
Purchase                      0
dtype: int64

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 222349 entries, 0 to 263013
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     222349 non-null  int64
 1   Product_ID                  222349 non-null  object
 2   Gender                      222349 non-null  object
 3   Age                         222349 non-null  object
 4   Occupation                  222349 non-null  float64
 5   City_Category               222349 non-null  object
 6   Stay_In_Current_City_Years  222349 non-null  float64
 7   Marital_Status              222349 non-null  float64
 8   Product_Category_1          222349 non-null  float64
 9   Product_Category_2          222349 non-null  float64
 10  Product_Category_3          222349 non-null  float64
 11  Purchase                    222349 non-null  float64
dtypes: float64(7), int64(1), object(4)
memory usage: 22.1+ MB

In [23]:
from sklearn.preprocessing import LabelEncoder

label_mappings = {}

for i in data.columns:
  if data[i].dtype == 'object':
    le = LabelEncoder()
    data[i]=le.fit_transform(data[i])
    label_mappings[i]=dict(zip(le.classes_, le.transform(le.classes_)))
for column,mapping in label_mappings.items():
  print(f'Mapping for {column}:{mapping}')

Mapping for Product_ID:{'P00000142': np.int64(0), 'P00000242': np.int64(1), 'P00000342': np.int64(2), 'P00000442': np.int64(3), 'P00000542': np.int64(4), 'P00000642': np.int64(5), 'P00000742': np.int64(6), 'P00000842': np.int64(7), 'P00000942': np.int64(8), 'P00001042': np.int64(9), 'P00001142': np.int64(10), 'P00001242': np.int64(11), 'P00001342': np.int64(12), 'P00001442': np.int64(13), 'P00001542': np.int64(14), 'P00001642': np.int64(15), 'P00001742': np.int64(16), 'P00001842': np.int64(17), 'P00001942': np.int64(18), 'P00002042': np.int64(19), 'P00002142': np.int64(20), 'P00002242': np.int64(21), 'P00002342': np.int64(22), 'P00002442': np.int64(23), 'P00002542': np.int64(24), 'P00002642': np.int64(25), 'P00002742': np.int64(26), 'P00002842': np.int64(27), 'P00002942': np.int64(28), 'P00003042': np.int64(29), 'P00003142': np.int64(30), 'P00003242': np.int64(31), 'P00003342': np.int64(32), 'P00003442': np.int64(33), 'P00003542': np.int64(34), 'P00003642': np.int64(35), 'P00003742': np.int64(36), 'P00003842': np.int64(37), 'P00003942': np.int64(38), 'P00004042': np.int64(39), 'P00004142': np.int64(40), 'P00004242': np.int64(41), 'P00004342': np.int64(42), 'P00004442': np.int64(43), 'P00004542': np.int64(44), 'P00004642': np.int64(45), 'P00004742': np.int64(46), 'P00004842': np.int64(47), 'P00004942': np.int64(48), 'P00005042': np.int64(49), 'P00005142': np.int64(50), 'P00005242': np.int64(51), 'P00005342': np.int64(52), 'P00005442': np.int64(53), 'P00005542': np.int64(54), 'P00005642': np.int64(55), 'P00005742': np.int64(56), 'P00005842': np.int64(57), 'P00005942': np.int64(58), 'P00006042': np.int64(59), 'P00006142': np.int64(60), 'P00006242': np.int64(61), 'P00006342': np.int64(62), 'P00006442': np.int64(63), 'P00006542': np.int64(64), 'P00006742': np.int64(65), 'P00006842': np.int64(66), 'P00006942': np.int64(67), 'P00007042': np.int64(68), 'P00007142': np.int64(69), 'P00007242': np.int64(70), 'P00007342': np.int64(71), 'P00007442': np.int64(72), 'P00007542': np.int64(73), 'P00007642': np.int64(74), 'P00007742': np.int64(75), 'P00007842': np.int64(76), 'P00007942': np.int64(77), 'P00008042': np.int64(78), 'P00008142': np.int64(79), 'P00008242': np.int64(80), 'P00008342': np.int64(81), 'P00008442': np.int64(82), 'P00008542': np.int64(83), 'P00008642': np.int64(84), 'P00008742': np.int64(85), 'P00008842': np.int64(86), 'P00009042': np.int64(87), 'P00009142': np.int64(88), 'P00009242': np.int64(89), 'P00009342': np.int64(90), 'P00009442': np.int64(91), 'P00009542': np.int64(92), 'P00009642': np.int64(93), 'P00009742': np.int64(94), 'P00010042': np.int64(95), 'P00010142': np.int64(96), 'P00010242': np.int64(97), 'P00010342': np.int64(98), 'P00010442': np.int64(99), 'P00010542': np.int64(100), 'P00010642': np.int64(101), 'P00010742': np.int64(102), 'P00010842': np.int64(103), 'P00010942': np.int64(104), 'P00011042': np.int64(105), 'P00011142': np.int64(106), 'P00011242': np.int64(107), 'P00011342': np.int64(108), 'P00011442': np.int64(109), 'P00011542': np.int64(110), 'P00011642': np.int64(111), 'P00011742': np.int64(112), 'P00011842': np.int64(113), 'P00011942': np.int64(114), 'P00012042': np.int64(115), 'P00012142': np.int64(116), 'P00012242': np.int64(117), 'P00012442': np.int64(118), 'P00012542': np.int64(119), 'P00012742': np.int64(120), 'P00012842': np.int64(121), 'P00012942': np.int64(122), 'P00013142': np.int64(123), 'P00013242': np.int64(124), 'P00013342': np.int64(125), 'P00013442': np.int64(126), 'P00013542': np.int64(127), 'P00013642': np.int64(128), 'P00013742': np.int64(129), 'P00013942': np.int64(130), 'P00014042': np.int64(131), 'P00014142': np.int64(132), 'P00014242': np.int64(133), 'P00014342': np.int64(134), 'P00014442': np.int64(135), 'P00014542': np.int64(136), 'P00014642': np.int64(137), 'P00014742': np.int64(138), 'P00014842': np.int64(139), 'P00014942': np.int64(140), 'P00015042': np.int64(141), 'P00015142': np.int64(142), 'P00015242': np.int64(143), 'P00015342': np.int64(144), 'P00015442': np.int64(145), 'P00015542': np.int64(146), 'P00015642': np.int64(147), 'P00015742': np.int64(148), 'P00015842': np.int64(149), 'P00015942': np.int64(150), 'P00016042': np.int64(151), 'P00016142': np.int64(152), 'P00016242': np.int64(153), 'P00016342': np.int64(154), 'P00016442': np.int64(155), 'P00016542': np.int64(156), 'P00016642': np.int64(157), 'P00016742': np.int64(158), 'P00016842': np.int64(159), 'P00016942': np.int64(160), 'P00017042': np.int64(161), 'P00017142': np.int64(162), 'P00017242': np.int64(163), 'P00017342': np.int64(164), 'P00017442': np.int64(165), 'P00017542': np.int64(166), 'P00017642': np.int64(167), 'P00017742': np.int64(168), 'P00017842': np.int64(169), 'P00017942': np.int64(170), 'P00018042': np.int64(171), 'P00018142': np.int64(172), 'P00018242': np.int64(173), 'P00018342': np.int64(174), 'P00018442': np.int64(175), 'P00018542': np.int64(176), 'P00018642': np.int64(177), 'P00018742': np.int64(178), 'P00018842': np.int64(179), 'P00018942': np.int64(180), 'P00019042': np.int64(181), 'P00019142': np.int64(182), 'P00019242': np.int64(183), 'P00019342': np.int64(184), 'P00019442': np.int64(185), 'P00019542': np.int64(186), 'P00019642': np.int64(187), 'P00019742': np.int64(188), 'P00019842': np.int64(189), 'P00019942': np.int64(190), 'P00020042': np.int64(191), 'P00020142': np.int64(192), 'P00020242': np.int64(193), 'P00020342': np.int64(194), 'P00020442': np.int64(195), 'P00020542': np.int64(196), 'P00020642': np.int64(197), 'P00020742': np.int64(198), 'P00020842': np.int64(199), 'P00020942': np.int64(200), 'P00021042': np.int64(201), 'P00021142': np.int64(202), 'P00021242': np.int64(203), 'P00021342': np.int64(204), 'P00021442': np.int64(205), 'P00021542': np.int64(206), 'P00021642': np.int64(207), 'P00021742': np.int64(208), 'P00021842': np.int64(209), 'P00021942': np.int64(210), 'P00022142': np.int64(211), 'P00022242': np.int64(212), 'P00022342': np.int64(213), 'P00022442': np.int64(214), 'P00022542': np.int64(215), 'P00022642': np.int64(216), 'P00022742': np.int64(217), 'P00022842': np.int64(218), 'P00022942': np.int64(219), 'P00023042': np.int64(220), 'P00023142': np.int64(221), 'P00023242': np.int64(222), 'P00023342': np.int64(223), 'P00023442': np.int64(224), 'P00023542': np.int64(225), 'P00023642': np.int64(226), 'P00023742': np.int64(227), 'P00023842': np.int64(228), 'P00023942': np.int64(229), 'P00024042': np.int64(230), 'P00024142': np.int64(231), 'P00024242': np.int64(232), 'P00024342': np.int64(233), 'P00024442': np.int64(234), 'P00024542': np.int64(235), 'P00024642': np.int64(236), 'P00024742': np.int64(237), 'P00024842': np.int64(238), 'P00024942': np.int64(239), 'P00025042': np.int64(240), 'P00025142': np.int64(241), 'P00025242': np.int64(242), 'P00025342': np.int64(243), 'P00025442': np.int64(244), 'P00025542': np.int64(245), 'P00025642': np.int64(246), 'P00025742': np.int64(247), 'P00025942': np.int64(248), 'P00026042': np.int64(249), 'P00026142': np.int64(250), 'P00026242': np.int64(251), 'P00026342': np.int64(252), 'P00026442': np.int64(253), 'P00026542': np.int64(254), 'P00026642': np.int64(255), 'P00026742': np.int64(256), 'P00026842': np.int64(257), 'P00026942': np.int64(258), 'P00027042': np.int64(259), 'P00027142': np.int64(260), 'P00027242': np.int64(261), 'P00027342': np.int64(262), 'P00027442': np.int64(263), 'P00027542': np.int64(264), 'P00027642': np.int64(265), 'P00027742': np.int64(266), 'P00027942': np.int64(267), 'P00028042': np.int64(268), 'P00028142': np.int64(269), 'P00028242': np.int64(270), 'P00028342': np.int64(271), 'P00028442': np.int64(272), 'P00028542': np.int64(273), 'P00028642': np.int64(274), 'P00028742': np.int64(275), 'P00028842': np.int64(276), 'P00028942': np.int64(277), 'P00029042': np.int64(278), 'P00029142': np.int64(279), 'P00029242': np.int64(280), 'P00029342': np.int64(281), 'P00029442': np.int64(282), 'P00029542': np.int64(283), 'P00029642': np.int64(284), 'P00029742': np.int64(285), 'P00029842': np.int64(286), 'P00029942': np.int64(287), 'P00030042': np.int64(288), 'P00030142': np.int64(289), 'P00030442': np.int64(290), 'P00030542': np.int64(291), 'P00030642': np.int64(292), 'P00030742': np.int64(293), 'P00030842': np.int64(294), 'P00030942': np.int64(295), 'P00031042': np.int64(296), 'P00031142': np.int64(297), 'P00031242': np.int64(298), 'P00031342': np.int64(299), 'P00031442': np.int64(300), 'P00031542': np.int64(301), 'P00031642': np.int64(302), 'P00031742': np.int64(303), 'P00031842': np.int64(304), 'P00031942': np.int64(305), 'P00032042': np.int64(306), 'P00032142': np.int64(307), 'P00032242': np.int64(308), 'P00032342': np.int64(309), 'P00032442': np.int64(310), 'P00032542': np.int64(311), 'P00032642': np.int64(312), 'P00032742': np.int64(313), 'P00032842': np.int64(314), 'P00032942': np.int64(315), 'P00033042': np.int64(316), 'P00033142': np.int64(317), 'P00033242': np.int64(318), 'P00033342': np.int64(319), 'P00033442': np.int64(320), 'P00033542': np.int64(321), 'P00033642': np.int64(322), 'P00033742': np.int64(323), 'P00033842': np.int64(324), 'P00033942': np.int64(325), 'P00034042': np.int64(326), 'P00034142': np.int64(327), 'P00034242': np.int64(328), 'P00034342': np.int64(329), 'P00034442': np.int64(330), 'P00034542': np.int64(331), 'P00034642': np.int64(332), 'P00034742': np.int64(333), 'P00034842': np.int64(334), 'P00034942': np.int64(335), 'P00035042': np.int64(336), 'P00035142': np.int64(337), 'P00035242': np.int64(338), 'P00035342': np.int64(339), 'P00035442': np.int64(340), 'P00035542': np.int64(341), 'P00035642': np.int64(342), 'P00035742': np.int64(343), 'P00035842': np.int64(344), 'P00035942': np.int64(345), 'P00036042': np.int64(346), 'P00036142': np.int64(347), 'P00036242': np.int64(348), 'P00036342': np.int64(349), 'P00036442': np.int64(350), 'P00036542': np.int64(351), 'P00036642': np.int64(352), 'P00036742': np.int64(353), 'P00036842': np.int64(354), 'P00036942': np.int64(355), 'P00037042': np.int64(356), 'P00037142': np.int64(357), 'P00037242': np.int64(358), 'P00037342': np.int64(359), 'P00037442': np.int64(360), 'P00037542': np.int64(361), 'P00037642': np.int64(362), 'P00037742': np.int64(363), 'P00037842': np.int64(364), 'P00037942': np.int64(365), 'P00038042': np.int64(366), 'P00038142': np.int64(367), 'P00038242': np.int64(368), 'P00038342': np.int64(369), 'P00038442': np.int64(370), 'P00038542': np.int64(371), 'P00038742': np.int64(372), 'P00039142': np.int64(373), 'P00039242': np.int64(374), 'P00039342': np.int64(375), 'P00039442': np.int64(376), 'P00039542': np.int64(377), 'P00039642': np.int64(378), 'P00039742': np.int64(379), 'P00039842': np.int64(380), 'P00039942': np.int64(381), 'P00040042': np.int64(382), 'P00040142': np.int64(383), 'P00040242': np.int64(384), 'P00040342': np.int64(385), 'P00040442': np.int64(386), 'P00040542': np.int64(387), 'P00040642': np.int64(388), 'P00040742': np.int64(389), 'P00040842': np.int64(390), 'P00040942': np.int64(391), 'P00041042': np.int64(392), 'P00041142': np.int64(393), 'P00041242': np.int64(394), 'P00041342': np.int64(395), 'P00041442': np.int64(396), 'P00041542': np.int64(397), 'P00041642': np.int64(398), 'P00041742': np.int64(399), 'P00041842': np.int64(400), 'P00041942': np.int64(401), 'P00042042': np.int64(402), 'P00042142': np.int64(403), 'P00042242': np.int64(404), 'P00042342': np.int64(405), 'P00042442': np.int64(406), 'P00042542': np.int64(407), 'P00042742': np.int64(408), 'P00042842': np.int64(409), 'P00042942': np.int64(410), 'P00043042': np.int64(411), 'P00043142': np.int64(412), 'P00043242': np.int64(413), 'P00043342': np.int64(414), 'P00043442': np.int64(415), 'P00043542': np.int64(416), 'P00043642': np.int64(417), 'P00043742': np.int64(418), 'P00043842': np.int64(419), 'P00043942': np.int64(420), 'P00044042': np.int64(421), 'P00044142': np.int64(422), 'P00044242': np.int64(423), 'P00044342': np.int64(424), 'P00044442': np.int64(425), 'P00044542': np.int64(426), 'P00044642': np.int64(427), 'P00044742': np.int64(428), 'P00044842': np.int64(429), 'P00044942': np.int64(430), 'P00045042': np.int64(431), 'P00045142': np.int64(432), 'P00045242': np.int64(433), 'P00045342': np.int64(434), 'P00045442': np.int64(435), 'P00045542': np.int64(436), 'P00045642': np.int64(437), 'P00045742': np.int64(438), 'P00045842': np.int64(439), 'P00045942': np.int64(440), 'P00046042': np.int64(441), 'P00046142': np.int64(442), 'P00046242': np.int64(443), 'P00046342': np.int64(444), 'P00046442': np.int64(445), 'P00046542': np.int64(446), 'P00046642': np.int64(447), 'P00046742': np.int64(448), 'P00046842': np.int64(449), 'P00046942': np.int64(450), 'P00047042': np.int64(451), 'P00047142': np.int64(452), 'P00047242': np.int64(453), 'P00047342': np.int64(454), 'P00047442': np.int64(455), 'P00047542': np.int64(456), 'P00047642': np.int64(457), 'P00047742': np.int64(458), 'P00047842': np.int64(459), 'P00047942': np.int64(460), 'P00048042': np.int64(461), 'P00048142': np.int64(462), 'P00048242': np.int64(463), 'P00048342': np.int64(464), 'P00048442': np.int64(465), 'P00048542': np.int64(466), 'P00048642': np.int64(467), 'P00048742': np.int64(468), 'P00048842': np.int64(469), 'P00048942': np.int64(470), 'P00049042': np.int64(471), 'P00049142': np.int64(472), 'P00049242': np.int64(473), 'P00049342': np.int64(474), 'P00049442': np.int64(475), 'P00049542': np.int64(476), 'P00049642': np.int64(477), 'P00049742': np.int64(478), 'P00049842': np.int64(479), 'P00049942': np.int64(480), 'P00050042': np.int64(481), 'P00050142': np.int64(482), 'P00050242': np.int64(483), 'P00050342': np.int64(484), 'P00050442': np.int64(485), 'P00050542': np.int64(486), 'P00050642': np.int64(487), 'P00050742': np.int64(488), 'P00050842': np.int64(489), 'P00050942': np.int64(490), 'P00051042': np.int64(491), 'P00051142': np.int64(492), 'P00051242': np.int64(493), 'P00051342': np.int64(494), 'P00051442': np.int64(495), 'P00051542': np.int64(496), 'P00051642': np.int64(497), 'P00051742': np.int64(498), 'P00051842': np.int64(499), 'P00051942': np.int64(500), 'P00052042': np.int64(501), 'P00052142': np.int64(502), 'P00052242': np.int64(503), 'P00052342': np.int64(504), 'P00052442': np.int64(505), 'P00052542': np.int64(506), 'P00052642': np.int64(507), 'P00052742': np.int64(508), 'P00052842': np.int64(509), 'P00052942': np.int64(510), 'P00053042': np.int64(511), 'P00053142': np.int64(512), 'P00053342': np.int64(513), 'P00053442': np.int64(514), 'P00053542': np.int64(515), 'P00053642': np.int64(516), 'P00053742': np.int64(517), 'P00053842': np.int64(518), 'P00053942': np.int64(519), 'P00054042': np.int64(520), 'P00054142': np.int64(521), 'P00054242': np.int64(522), 'P00054342': np.int64(523), 'P00054442': np.int64(524), 'P00054542': np.int64(525), 'P00054742': np.int64(526), 'P00054842': np.int64(527), 'P00054942': np.int64(528), 'P00055042': np.int64(529), 'P00055142': np.int64(530), 'P00055242': np.int64(531), 'P00055342': np.int64(532), 'P00055442': np.int64(533), 'P00055542': np.int64(534), 'P00055642': np.int64(535), 'P00055742': np.int64(536), 'P00055842': np.int64(537), 'P00055942': np.int64(538), 'P00056042': np.int64(539), 'P00056142': np.int64(540), 'P00056242': np.int64(541), 'P00056442': np.int64(542), 'P00056542': np.int64(543), 'P00056742': np.int64(544), 'P00056842': np.int64(545), 'P00057042': np.int64(546), 'P00057242': np.int64(547), 'P00057342': np.int64(548), 'P00057442': np.int64(549), 'P00057542': np.int64(550), 'P00057642': np.int64(551), 'P00057742': np.int64(552), 'P00057942': np.int64(553), 'P00058042': np.int64(554), 'P00058142': np.int64(555), 'P00058242': np.int64(556), 'P00058342': np.int64(557), 'P00058442': np.int64(558), 'P00058642': np.int64(559), 'P00058742': np.int64(560), 'P00058942': np.int64(561), 'P00059042': np.int64(562), 'P00059142': np.int64(563), 'P00059242': np.int64(564), 'P00059342': np.int64(565), 'P00059442': np.int64(566), 'P00059542': np.int64(567), 'P00059642': np.int64(568), 'P00059742': np.int64(569), 'P00059842': np.int64(570), 'P00059942': np.int64(571), 'P00060042': np.int64(572), 'P00060142': np.int64(573), 'P00060242': np.int64(574), 'P00060442': np.int64(575), 'P00060542': np.int64(576), 'P00060642': np.int64(577), 'P00060942': np.int64(578), 'P00061042': np.int64(579), 'P00061142': np.int64(580), 'P00061242': np.int64(581), 'P00061342': np.int64(582), 'P00061442': np.int64(583), 'P00061542': np.int64(584), 'P00061742': np.int64(585), 'P00061842': np.int64(586), 'P00061942': np.int64(587), 'P00062042': np.int64(588), 'P00062142': np.int64(589), 'P00062642': np.int64(590), 'P00062742': np.int64(591), 'P00062842': np.int64(592), 'P00062942': np.int64(593), 'P00063042': np.int64(594), 'P00063242': np.int64(595), 'P00063342': np.int64(596), 'P00063542': np.int64(597), 'P00063842': np.int64(598), 'P00064042': np.int64(599), 'P00064142': np.int64(600), 'P00064242': np.int64(601), 'P00064342': np.int64(602), 'P00064442': np.int64(603), 'P00064642': np.int64(604), 'P00064742': np.int64(605), 'P00064842': np.int64(606), 'P00064942': np.int64(607), 'P00065042': np.int64(608), 'P00065242': np.int64(609), 'P00065342': np.int64(610), 'P00065442': np.int64(611), 'P00065642': np.int64(612), 'P00065742': np.int64(613), 'P00066042': np.int64(614), 'P00066142': np.int64(615), 'P00066242': np.int64(616), 'P00066342': np.int64(617), 'P00066442': np.int64(618), 'P00066542': np.int64(619), 'P00066642': np.int64(620), 'P00066742': np.int64(621), 'P00066942': np.int64(622), 'P00067042': np.int64(623), 'P00067142': np.int64(624), 'P00067342': np.int64(625), 'P00067442': np.int64(626), 'P00067542': np.int64(627), 'P00067642': np.int64(628), 'P00067742': np.int64(629), 'P00067842': np.int64(630), 'P00067942': np.int64(631), 'P00068042': np.int64(632), 'P00068142': np.int64(633), 'P00068242': np.int64(634), 'P00068442': np.int64(635), 'P00068542': np.int64(636), 'P00068642': np.int64(637), 'P00068842': np.int64(638), 'P00068942': np.int64(639), 'P00069042': np.int64(640), 'P00069142': np.int64(641), 'P00069242': np.int64(642), 'P00069342': np.int64(643), 'P00069442': np.int64(644), 'P00069542': np.int64(645), 'P00069642': np.int64(646), 'P00069842': np.int64(647), 'P00069942': np.int64(648), 'P00070042': np.int64(649), 'P00070142': np.int64(650), 'P00070242': np.int64(651), 'P00070342': np.int64(652), 'P00070442': np.int64(653), 'P00070542': np.int64(654), 'P00070642': np.int64(655), 'P00070742': np.int64(656), 'P00070942': np.int64(657), 'P00071042': np.int64(658), 'P00071142': np.int64(659), 'P00071242': np.int64(660), 'P00071342': np.int64(661), 'P00071442': np.int64(662), 'P00071542': np.int64(663), 'P00071642': np.int64(664), 'P00071742': np.int64(665), 'P00071842': np.int64(666), 'P00071942': np.int64(667), 'P00072242': np.int64(668), 'P00072342': np.int64(669), 'P00072442': np.int64(670), 'P00072542': np.int64(671), 'P00072742': np.int64(672), 'P00072842': np.int64(673), 'P00072942': np.int64(674), 'P00073042': np.int64(675), 'P00073142': np.int64(676), 'P00073242': np.int64(677), 'P00073542': np.int64(678), 'P00073642': np.int64(679), 'P00073742': np.int64(680), 'P00073842': np.int64(681), 'P00073942': np.int64(682), 'P00074042': np.int64(683), 'P00074142': np.int64(684), 'P00074242': np.int64(685), 'P00074342': np.int64(686), 'P00074442': np.int64(687), 'P00074542': np.int64(688), 'P00074642': np.int64(689), 'P00075142': np.int64(690), 'P00075242': np.int64(691), 'P00075342': np.int64(692), 'P00075442': np.int64(693), 'P00075542': np.int64(694), 'P00075642': np.int64(695), 'P00075742': np.int64(696), 'P00075842': np.int64(697), 'P00075942': np.int64(698), 'P00076042': np.int64(699), 'P00076142': np.int64(700), 'P00076242': np.int64(701), 'P00076342': np.int64(702), 'P00076442': np.int64(703), 'P00076542': np.int64(704), 'P00076642': np.int64(705), 'P00076742': np.int64(706), 'P00076942': np.int64(707), 'P00077042': np.int64(708), 'P00077142': np.int64(709), 'P00077442': np.int64(710), 'P00077542': np.int64(711), 'P00077742': np.int64(712), 'P00077842': np.int64(713), 'P00077942': np.int64(714), 'P00078042': np.int64(715), 'P00078142': np.int64(716), 'P00078242

In [24]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,640,0,0,10.0,0,2.0,0.0,3.0,0.0,0.0,8370.0
1,1000001,2282,0,0,10.0,0,2.0,0.0,1.0,6.0,14.0,15200.0
2,1000001,805,0,0,10.0,0,2.0,0.0,12.0,0.0,0.0,1422.0
3,1000001,781,0,0,10.0,0,2.0,0.0,12.0,14.0,0.0,1057.0
5,1000003,1751,1,2,15.0,0,3.0,0.0,1.0,2.0,0.0,15227.0
...,...,...,...,...,...,...,...,...,...,...,...,...
263009,1004473,2736,1,3,1.0,1,3.0,0.0,8.0,0.0,0.0,8061.0
263010,1004473,401,1,3,1.0,1,3.0,0.0,5.0,18.0,0.0,3722.0
263011,1004473,1004,1,3,1.0,1,3.0,0.0,1.0,8.0,17.0,19253.0
263012,1004473,1700,1,3,1.0,1,3.0,0.0,5.0,7.0,0.0,3608.0
263013,1004473,1047,1,3,1.0,1,3.0,0.0,5.0,0.0,0.0,3604.0

In [25]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 222349 entries, 0 to 263013
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     222349 non-null  int64
 1   Product_ID                  222349 non-null  int64
 2   Gender                      222349 non-null  int64
 3   Age                         222349 non-null  int64
 4   Occupation                  222349 non-null  float64
 5   City_Category               222349 non-null  int64
 6   Stay_In_Current_City_Years  222349 non-null  float64
 7   Marital_Status              222349 non-null  float64
 8   Product_Category_1          222349 non-null  float64
 9   Product_Category_2          222349 non-null  float64
 10  Product_Category_3          222349 non-null  float64
 11  Purchase                    222349 non-null  float64
dtypes: float64(7), int64(5)
memory usage: 22.1 MB

In [ ]:
#Statistic analysis
#Steps perform hypothesis Testing:
#1. Data collection
#2. preparing samples
#3. creating two hypothesis(null, alternate)
#4. applying the appropriate test (based on requirement)
#5. if p-value < 0.05 reject of null hypothesis
#    if p-value > 0.05 fail to reject null hypothesis

In [26]:
#a. It was observed that the average purchase made by men of the age 18-25 was 10000. Is it still the same?

newData = data[(data['Age']==1) & data['Gender']==1]
newData

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
97,1000021,2004,1,1,16.0,1,0.0,0.0,3.0,12.0,0.0,3055.0
220,1000039,2574,1,1,4.0,1,2.0,0.0,16.0,0.0,0.0,12464.0
221,1000039,3228,1,1,4.0,1,2.0,0.0,1.0,8.0,17.0,15319.0
300,1000052,1320,1,1,4.0,2,0.0,0.0,1.0,16.0,0.0,15244.0
301,1000052,5,1,1,4.0,2,0.0,0.0,1.0,6.0,16.0,19060.0
...,...,...,...,...,...,...,...,...,...,...,...,...
262767,1004446,1298,1,1,18.0,1,1.0,1.0,1.0,2.0,0.0,15431.0
262951,1004465,2850,1,1,4.0,0,1.0,1.0,5.0,0.0,0.0,1763.0
262952,1004465,1283,1,1,4.0,0,1.0,1.0,2.0,3.0,4.0,3240.0
262953,1004465,2707,1,1,4.0,0,1.0,1.0,8.0,0.0,0.0,5832.0
262954,1004465,1409,1,1,4.0,0,1.0,1.0,8.0,0.0,0.0,7788.0

In [27]:
newData['Purchase'].mean()

np.float64(9466.768918692373)

In [29]:
sample = newData.sample(3600,random_state=5)
sample

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
190087,1005367,102,1,1,4.0,0,1.0,0.0,1.0,8.0,17.0,15649.0
12234,1001842,50,1,1,4.0,1,1.0,0.0,5.0,0.0,0.0,6880.0
50865,1001764,2079,1,1,0.0,1,1.0,0.0,2.0,5.0,0.0,13013.0
82254,1000714,3265,1,1,4.0,1,2.0,0.0,1.0,15.0,0.0,19441.0
203050,1001329,3105,1,1,14.0,1,3.0,0.0,5.0,0.0,0.0,3487.0
...,...,...,...,...,...,...,...,...,...,...,...,...
156647,1000192,535,1,1,1.0,1,2.0,0.0,4.0,5.0,0.0,758.0
67977,1004401,1772,1,1,4.0,0,3.0,0.0,5.0,0.0,0.0,5326.0
156458,1000163,569,1,1,4.0,0,1.0,0.0,1.0,11.0,15.0,4207.0
255089,1003391,1250,1,1,4.0,0,0.0,0.0,1.0,6.0,14.0,4503.0
929,1000163,1762,1,1,4.0,0,1.0,0.0,1.0,6.0,13.0,8081.0

In [31]:
from scipy.stats import ttest_1samp
alternateMean = 10000
t_stat, p_value = ttest_1samp(sample['Purchase'],alternateMean)
print(t_stat,p_value)

-4.894716313857535 1.0276926610435886e-06

In [32]:
#b. It was observed that percentage of women that spend more then 10000 was 35%. Is it still the same?
#null hypo = proportion is 35%
#alternate hypo = proportion is not 35%

ndata = data[(data['Purchase'])>10000]
ndata

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
1,1000001,2282,0,0,10.0,0,2.0,0.0,1.0,6.0,14.0,15200.0
5,1000003,1751,1,2,15.0,0,3.0,0.0,1.0,2.0,0.0,15227.0
6,1000004,1668,1,4,7.0,1,2.0,1.0,1.0,8.0,17.0,19215.0
7,1000004,3180,1,4,7.0,1,2.0,1.0,1.0,15.0,0.0,15854.0
8,1000004,3448,1,4,7.0,1,2.0,1.0,1.0,16.0,0.0,15686.0
...,...,...,...,...,...,...,...,...,...,...,...,...
262997,1004472,2411,0,4,16.0,1,0.0,1.0,1.0,11.0,16.0,15175.0
263001,1004472,1901,0,4,16.0,1,0.0,1.0,1.0,11.0,15.0,15430.0
263002,1004472,1649,0,4,16.0,1,0.0,1.0,15.0,16.0,0.0,12567.0
263003,1004472,3176,0,4,16.0,1,0.0,1.0,1.0,2.0,15.0,15387.0
263011,1004473,1004,1,3,1.0,1,3.0,0.0,1.0,8.0,17.0,19253.0

In [33]:
ndata['Gender'].value_counts()

Gender
1    60887
0    16142
Name: count, dtype: int64

In [34]:
#Number of women in the sample
count = ndata['Gender'].value_counts()[0]

#Number of observations
nobs = len(ndata['Gender'])

#hypothesised value
p0 = 0.35

count,nobs,p0

(np.int64(16142), 77029, 0.35)

In [35]:
16142/77029

0.20955743940593802

In [38]:
from statsmodels.stats.proportion import proportions_ztest
z_stat, p_value = proportions_ztest(count = count, nobs = nobs, value = p0)
print(z_stat,p_value)

-95.7721350421428 0.0

-95.7721350421428 0.0